<!--
	Ensygnia Onescan extension
	Copyright (C) 2014 Ensygnia Ltd

	This program is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->
<div class="onescan-notice">
    <h4><?php echo Mage::helper('onescan')->__('Sign up for'); ?> <a href="https://portal.ensygnia.net" target="_blank">Onescan</a> by Ensygnia.</h4>
    <h4><?php echo Mage::helper('onescan')->__('Download the manual from'); ?> <a href="http://www.ensygnia.com/downloads/OnescanPaymentPlugin.pdf" target="_blank">http://www.ensygnia.com/downloads/OnescanPaymentPlugin.pdf</a>.</h4>
</div>