<?php
/*
	Ensygnia Onescan extension
	Copyright (C) 2014 Ensygnia Ltd

	This program is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
	global $basketPadlockCount;
	if (!isset($basketPadlockCount)) {
		$basketPadlockCount=1;
	} else {
		$basketPadlockCount++;
	}
?>
<?php if ($this->getOnescanHelper()->isEnabled()): ?>
	<div class="block block-onescan block-onescan-basket">
		<div class="block-title">
			<strong><span>Pay with Onescan</span></strong>
		</div>

		<div class="block-content">
			<?php if ($this->hasItems()) { ?>
				<div id="onescanPadlock_basket<?php echo $basketPadlockCount; ?>" class="onescanPadlock_basket onescanpadlock"
					data-sessionurl="<?php echo $this->getOnescanHelper()->getSessionFromBasketUrl() . '?basket=' . $basketPadlockCount; ?>"
					data-postconfirm="postConfirm(<?php echo $basketPadlockCount; ?>);"  data-postfailed="postFailed();"
					data-polltarget="<?php echo $this->getOnescanHelper()->getSessionPollUrl(); ?>" data-nonescan="true">
				</div>
			<?php } ?>
		</div>
	</div>
<?php endif; ?>